version: '3'

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./encryption/config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
    app:
        build: app/
        command: python -u app.py
        volumes:
            - ./app:/app/
        ports:
            - "5000:5000"
        depends_on:
            - redis